name = "Airborn Exploration"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ff2957cea244ba5c0558463f5e9f8f00bcb764c18207f421d1245ac7f773db2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
