name = "Airborn Exploration"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39436f591638d4233576288187e8de457eaae9f533e64b162f2bfa8c8ad729da"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"

[options]
acceptable-game-versions = []
